### ISSUE TITLE
License

### ISSUE THREAD

**Issue by coroa** [balzer82/immoscraper#2]
Hi balzer82,

thanks for your beautifully commented scraper and analysis notebooks :). They will be giving me a fair headstart for my own small project. Do you mind putting your work under some open licence, so I can just build on your notebooks!

There is a helpful guide at https://www.software.ac.uk/resources/guides/adopting-open-source-licence

But I always thought the open licence jungle is best mapped out in the license-chart by Robbie Morrisson: 
![license-chart](https://user-images.githubusercontent.com/2552981/44683095-98ee0080-aa45-11e8-8970-cfb0bc51f240.png)

Thanks,
Jonas

**Comment by balzer82** [comment]
You are welcome
